# -*- coding: utf-8 -*-
"""Assignment1_CS_201951164.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WDI_G4Oq0EZro_7Wq5oY8p0HATD-E9nN

Question 1
"""

import pandas as pd
import json
import sys
data = pd.read_csv("district_level_service_msme.csv")
print(data)

"""Question 2"""

file_directory = "district_level_manufacturing_msme.json"
f = open(file_directory)
loaded_data = json.load(f)
columns = pd.DataFrame(loaded_data["fields"])["label"].tolist()
var_data = pd.DataFrame(loaded_data["data"],columns = columns)
print(var_data)

"""first convert the data  then find out the total small  Manufacturing MSME in india"""

small_Data = var_data["SMALL"].astype(int).sum(axis = 0, skipna = True) #First we will convert the data from string to in then we will sum it
print(small_Data)

"""Question 3"""

total_Data = data.groupby("STATE_NAME")["MICRO","SMALL","MEDIUM"].sum()
print(total_Data)
file_directory = ("201951164_Urmila.csv")
total_Data.to_csv(file_directory)

"""Question 4"""

data['Lg_Dist_Code']=data['Lg_Dist_Code'].apply(str)
data['Last_Updated']=data['Last_Updated'].apply(str)
var_data['Lg_Dist_Code']=var_data['Lg_Dist_Code'].apply(str)
var_data['Last_Updated']=var_data['Last_Updated'].apply(str)
join_Data = pd.merge(var_data,data,on=['STATE_NAME','DISTRICT_NAME','Lg_Dist_Code','Last_Updated'],how='inner')
print(join_Data)

"""Question 5"""

var_data['MICRO']=var_data['MICRO'].astype(int)
var_data['SMALL']=var_data['SMALL'].astype(int)
var_data['MEDIUM']=var_data['MEDIUM'].astype(int)
second_total_Data = var_data.groupby('STATE_NAME')['MICRO','SMALL','MEDIUM'].sum()
pivot_Data = pd.merge(total_Data,second_total_Data,on='STATE_NAME')
print(pivot_Data)