# -*- coding: utf-8 -*-
"""Assignment2_CS_201951164

Automatically generated by Colaboratory.



import pandas as pd
import pandas.util.testing as tm
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.graphics.gofplots import qqplot

data_jk =pd.read_csv("/content/JK-Allopathic-Outpatient_attendance-May-2019 - JK-Allopathic-Outpatient_attendance-May-2019.csv")
data_fifa = pd.read_csv("/content/Fifa_player_football_data - Fifa_player_football_data.csv")

data=data_jk.drop(columns=['Facility Type', 'Total No. of Facilities #','No. of facilities reporting nil performance *','Performance - Overall Average **','Performance - Maximum','Performance - Minimum'])
data_q1=data.groupby("District").sum()
#data_q1.reset_index(level=0, inplace=True)
data_q1.plot(kind='bar',figsize=(15,8),legend = 'upper right',xlabel='Districts',ylabel='patient attendance')

data_q3=data_jk.drop(columns=['Total No. of Facilities #','No. of facilities reporting nil performance *','Performance - Maximum','Performance - Minimum','No. of facilities by performance - 1 to 100','No. of facilities by performance - 101 to 500','No. of facilities by performance - 501 to 1000','No. of facilities by performance - >1000'])
idx=data_q3['District'].isin(["Anantnag","Jammu",'Poonch','Reasi','Udhampur'])
data_q3=data_q3[idx]
ax=sns.barplot(x="District",
           y="Performance - Overall Average **",
           hue="Facility Type",   
           data=data_q3)
ax.set_yscale("log")

data_q4=data_jk.groupby(["District"]).agg(count=("Performance - Maximum", 'sum'))
data_q4=data_q4.reset_index()
data_q4=data_q4.iloc[0:20]
sns.scatterplot(data=data_q4, x="count", y="District")

data["Age"]=data_fifa[["Age"]]
sns.histplot(data=data, x="Age",kde=True,bins=7,color="g")

data["Age"]=data_fifa[["Age"]]
sns.histplot(data=data, x="Age",kde=True,bins=7,color="g")

idx=data_fifa["Club"].isin(["FC Barcelona","Chelsea","Juventus","Real Madrid"])
data_fifa=data_fifa[idx]

sns.kdeplot(data=data_fifa, x="Age", hue="Club",legend="upper right")

data_q3 = data_fifa[['Name','Value','Preferred Foot']]



sns.histplot(data=data_q3, x="Value", hue="Preferred Foot", multiple="stack")

qqplot(data_fifa["International Reputation"],line='s')
plt.show()